[package]
name = "craiyon-bot"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21", features = ["signal", "macros", "rt"] }
tgbotapi = { git = "https://github.com/Syfaro/tgbotapi-rs" }
async-trait = "0.1"
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
url = "2.3"
serde = "1.0"
serde_json = "1.0"
image = "0.24"
base64 = "0.20.0-alpha"
time = { version = "0.3", features = ["serde", "serde-well-known", "macros"] }
dotenv = "0.15"
log = { version = "0.4", features = ["std"] }
colored = "2.0"
counter = "0.5"
charname = "0.2"
