[package]
name = "craiyon-bot"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
teloxide = { version = "0.10", features = ["nightly", "macros"] }
reqwest = "0.11"
serde = "1"
image = "0.24"
bytes = "1"
base64 = "0.20.0-alpha"
time = { version = "0.3", features = ["serde", "serde-well-known"] }
dotenv = "0.15"
log = "0.4"
simple_logger = "2.1"
