[package]
name = "craiyon-bot"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
teloxide = { version = "0.9", features = ["macros", "auto-send"] }
reqwest = "0.11"
serde = "1"
image = "0.24"
base64 = "0.20.0-alpha"
dotenv = "0.15"
log = "0.4"
simple_logger = "2.1.0"
