[package]
name = "craiyon-bot"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["signal", "macros", "rt"] }
tgbotapi = { git = "https://github.com/Syfaro/tgbotapi-rs" }
async-trait = "0.1"
reqwest = { version = "0.11", features = ["json"] }
serde = "1"
image = "0.24"
base64 = "0.20.0-alpha"
time = { version = "0.3", features = ["serde", "serde-well-known"] }
dotenv = "0.15"
log = "0.4"
simple_logger = "2.1"
counter = "0.5"
charname = "0.2"
