version: "3"

services:
  craiyon-bot:
    build: .
    environment:
      TDLIB_COMMIT_HASH: fd3154b28727df9e66423d64168fab1202d8c849
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      DB_ENCRYPTION_KEY: ${DB_ENCRYPTION_KEY}
      STABLEHORDE_TOKEN: ${STABLEHORDE_TOKEN}
      STABLEHORDE_CLIENT: ${STABLEHORDE_CLIENT}
      MAKERSUITE_API_KEY: ${MAKERSUITE_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
    volumes:
      - craiyon-bot:/app

volumes:
  craiyon-bot:
